### ISSUE TITLE
scheduler image

### ISSUE THREAD

**Issue by lesserror** [muriloschuck/test-k8s-scheduler#1]
Have you made any changes to the scheduler source code? Could you please show us the details about how to build the `docker.io/muriloschuck/my-scheduler:2.0` image? Thank you ~

**Comment by muriloschuck** [comment]
hi there
there are no changes to the source code, this image is straight to what is documented here: https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/#package-the-scheduler

**Comment by lesserror** [comment]
ok, I got it~
